### ISSUE TITLE
下载电子书时runtime error

### ISSUE THREAD

**Issue by ZiqianXie** [yann0917/dedao-dl#163]
dle bookid 显示完chapter ID以后出错
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/yann0917/dedao-dl/utils.parseFootNoteDelimiter(0xc003aed590?)
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:728 +0x2bb
github.com/yann0917/dedao-dl/utils.GenLineContentByElement(0xc0031358c0)
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:595 +0x4b
github.com/yann0917/dedao-dl/utils.OneByOneHtml({0xbcdc21, 0x4}, 0x14, 0xc000320460, {0xc000119000?, 0x203000?, 0x2?})
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:311 +0x259
github.com/yann0917/dedao-dl/utils.AllInOneHtml({0xc000118800, 0xa5, 0xc000133dc0?}, {0xc000119000, 0xa4, 0x100})
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:272 +0xc5
github.com/yann0917/dedao-dl/utils.Svg2Html({0xc00003c180, 0x56}, {0xc000118800?, 0xd003d0?, 0xc00018d400?}, {0xc000119000?, 0xc00018bb98?, 0x0?})
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:84 +0x5d
github.com/yann0917/dedao-dl/cmd/app.(*EBookDownload).Download(0xc0004f3d50)
	/Users/yabo/wwwroot/dedao-dl/cmd/app/download.go:181 +0x3b0
github.com/yann0917/dedao-dl/cmd/app.Download(...)
	/Users/yabo/wwwroot/dedao-dl/cmd/app/download.go:207
github.com/yann0917/dedao-dl/cmd.glob..func8(0x12878e0?, {0xc000229040?, 0x1, 0x1?})
	/Users/yabo/wwwroot/dedao-dl/cmd/download.go:88 +0xd4
github.com/spf13/cobra.(*Command).execute(0x12878e0, {0xc000228ff0, 0x1, 0x1})
	/Users/yabo/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1285380)
	/Users/yabo/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/yabo/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/yann0917/dedao-dl/cmd.Execute(...)
	/Users/yabo/wwwroot/dedao-dl/cmd/root.go:29
main.main()
	/Users/yabo/wwwroot/dedao-dl/main.go:17 +0x25
```

**Comment by ZiqianXie** [comment]
只有一本书是这样，其他都可以正常下载。

**Comment by yann0917** [comment]
> 只有一本书是这样，其他都可以正常下载。

书名是什么？

**Comment by ZiqianXie** [comment]
> > 只有一本书是这样，其他都可以正常下载。
> 
> 书名是什么？

智能机器人养成记
