### ISSUE TITLE
下载课程93失败

### ISSUE THREAD

**Issue by An-Li-magicloud** [yann0917/dedao-dl#54]
非常感谢您花时间来维护工具。

可能是因为93是比较早期的课程，在数据格式上有些不同，导致下载失败。

```Powershell
PS C:\Users\ali\workspace> docker run -v "C:\Users\ali\workspace\config.json:/app/config.json" -v "C:\Users\ali\workspace\output:/app/output" -it --rm dedao dl 93
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbdc3e3]

goroutine 1 [running]:
github.com/yann0917/dedao-dl/cmd.extractCourseDownloadData(0xc0003b6050, 0x0, 0xc, 0x1e, 0x1e)
        /build/cmd/download.go:200 +0x383
github.com/yann0917/dedao-dl/cmd.extractDownloadData(0xc0000f7100, 0xc0003b6050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/cmd/download.go:182 +0xf1
github.com/yann0917/dedao-dl/cmd.download(0xdca529, 0x8, 0x5d, 0x0, 0x0, 0xc000235d58)
        /build/cmd/download.go:78 +0x5cc
github.com/yann0917/dedao-dl/cmd.glob..func7(0x1522dc0, 0xc0000edd20, 0x1, 0x1, 0x0, 0x0)
        /build/cmd/download.go:36 +0x8b
github.com/spf13/cobra.(*Command).execute(0x1522dc0, 0xc0000edcf0, 0x1, 0x1, 0x1522dc0, 0xc0000edcf0)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x15241c0, 0x0, 0x0, 0xc000088058)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/yann0917/dedao-dl/cmd.Execute(...)
        /build/cmd/root.go:29
main.main()
        /build/main.go:17 +0x2e
```

**Comment by An-Li-magicloud** [comment]
560也是同样的错误。

**Comment by yann0917** [comment]
> 560也是同样的错误。

能否告知 93 号和 560 号是什么课程，我看下数据结构。

**Comment by An-Li-magicloud** [comment]
93: 万维钢·精英日课
560: 吴军·硅谷来信3（年度日更）

**Comment by HELoki** [comment]
相同的问题。

**Comment by HELoki** [comment]
> 

download.go 中第199行加个article.Audio != nil  就行了

**Comment by yann0917** [comment]
> 

- develop 分支15天已经改了，还没推 main 分支。这个问题出现的原因是有些课程只有文稿没有音频 。

- 迟迟没有 merge 的原因是发现了像年度日更这种大量课程下载的时候，有问题没解决。好像触发了得到的反爬虫，导致部分音频下载不下来。

**Comment by yann0917** [comment]
> > 
> 
> download.go 中第199行加个article.Audio != nil 就行了

develop 分支已经改了半个月了
迟迟没有 merge 的原因是发现了像年度日更这种大量课程下载的时候，有问题没解决。好像触发了得到的反爬虫，导致部分音频下载不下来。
